htl_typegrid.settings:
  type: config_object
  label: 'HTL Typegrid settings'
  mapping:
    fallback_media_uuid:
      type: string
      label: 'Fallback media UUID'
    image_style:
      type: string
      label: 'Card image style'
